name: gradle

# Controls when the action will run.
on:
  push:
    tags:
      - v*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: publish to plugin portal
        env:
          GRADLE_PLUGIN_PUBLISH_KEY: ${{ secrets.GRADLE_PLUGIN_PUBLISH_KEY }}
          GRADLE_PLUGIN_PUBLISH_SECRET: ${{ secrets.GRADLE_PLUGIN_PUBLISH_SECRET }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          ./gradlew publishPlugins -Dgradle.publish.key=$GRADLE_PLUGIN_PUBLISH_KEY -Dgradle.publish.secret=$GRADLE_PLUGIN_PUBLISH_SECRET